name: test

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      # - name : Install Dependencies (linux)
      #   if: matrix.os == 'ubuntu-latest'
      #   run: sudo apt-get install -y libpq-dev
      # - name : Install Dependencies (macOS)
      #   if: matrix.os == 'macOS-latest'
      #   run: brew install libpq
      # - name : Install Dependencies (windows)
      #   if: matrix.os == 'windows-latest'
      #   run: choco install postgresql
      - name: Install Dependencies (Download DB::Pg)
        # Download DB::Pg, unpack it, edit META6.json to remove 'ver<5>' from
        # the 'depends' section, and call zef to install it.
        run: |
          wget https://github.com/CurtTilmes/raku-dbpg#:~:text=with%20GitHub%20Desktop-,Download,-ZIP;
          unzip raku-dbpg-master.zip;
          cd raku-dbpg-master;
          sed -i 's/ver<5>//g' META6.json;
          zef install .
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
