name: test

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          #- ubuntu-latest
          - macOS-latest
          #- windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies libpq-dev
        if: matrix.os == 'macOS-latest'
        run: brew install libpq
      - name: Install Dependencies (Download DB::Pg)
        # Download DB::Pg, unpack it, edit META6.json to remove 'ver<5>' from
        # the 'depends' section, and call zef to install it. fixed sed.
        if: matrix.os == 'macOS-latest'
        run: |
          git clone https://github.com/CurtTilmes/raku-dbpg.git
          cd raku-dbpg;
          sed -i '.bk' -e 's/\:ver\<5\>//g'  META6.json;
          zef install --exclude="pq" .
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
